// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.sun.j2ee.blueprints.lodgingsupplier.pomessagebean;

import javax.xml.rpc.*;

public interface WebServiceBroker extends javax.xml.rpc.Service {
    public com.sun.j2ee.blueprints.lodgingsupplier.pomessagebean.BrokerServiceIntf getBrokerServiceIntfPort() throws ServiceException;
}
