// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.sun.j2ee.blueprints.airlinesupplier.pomessagebean;

public interface BrokerServiceIntf extends java.rmi.Remote {
    public java.lang.String submitDocument(java.lang.String string_1) throws 
        com.sun.j2ee.blueprints.airlinesupplier.pomessagebean.ProcessingException, com.sun.j2ee.blueprints.airlinesupplier.pomessagebean.InvalidDocumentException,  java.rmi.RemoteException;
}
