// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package com.sun.j2ee.blueprints.opc.financial;

import javax.xml.rpc.*;

public interface CreditCardService extends javax.xml.rpc.Service {
    public com.sun.j2ee.blueprints.opc.financial.CreditCardIntf getCreditCardIntfPort() throws ServiceException;
}
